### ISSUE TITLE
Location of source code

### ISSUE THREAD

**Issue by jjdestef3** [osehra-ocp/omnibus-care-plan#2]
Hi,  

Maybe I missed this but where are the source code repositories?

Thanks

**Comment by petercyli** [comment]
All of the github repositories under the osehra-ocp github site.
https://github.com/osehra-ocp/ocp-test-data
https://github.com/osehra-ocp/ocp-hapi-fhir-jpaserver
https://github.com/osehra-ocp/ocp-uaa
.........

**Comment by jjdestef3** [comment]
Thanks
